<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sm_laufliste"
 *
 * Auto generated by Extension Builder 2020-03-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Laufliste',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Stefan Matthes',
    'author_email' => 'stefan.matthes@branding-energy.de',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-10.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
